onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  bcrypt: true
  prisma: true
  sharp: true
  unrs-resolver: true

